spring:
  session:
    store-type: redis
  data:
    redis:
      host: 10.6.1.10
      password: 123456
      port: 6379
      database: 1
server:
  servlet:
    session:
      cookie:
        name: auth_session
        path: /
  port: 8081