spring:
  session:
    redis:
      namespace: auth:session
    store-type: redis
  data:
    redis:
      host: 10.6.1.10
      password: 123456
      port: 6379
      database: 1
      lettuce:
        pool:
          max-active: 1000
          max-idle: 10
          min-idle: 3
          max-wait: -1
server:
  servlet:
    session:
      cookie:
        name: auth_session
        path: /
  port: 8081